### ISSUE TITLE
Checklist for v5.11 Packaged Release - name to be determined

### ISSUE THREAD

**Issue by kensoh** [kelaberetiv/TagUI#642]
It has been 8 months since the last packaged release of v5.0 -
https://github.com/kelaberetiv/TagUI/releases/tag/v5.0.0

There is typically an intended gap between implementing new features / bug fixes and putting those stuffs in a new packaged release which users will use by default for installation. The gap will allow time for users to try out new features and giving feedback on what might be broken or improved on, before putting those stuff into packaged installations for use in production.

There are some bug fixes, some new features, some improvements in readme. But nothing specific around a theme. This release is meant to round up all those changes. [Siow Yi Sheng](https://github.com/siowyisheng) is joining AI Singapore and will be maintaining this project going forward. There is a new version of TagUI next year being explored, that is based on NodeJS. That will remove dependencies such as PhantomJS, CasperJS and dependencies of those projects.

Also, along with exploring the move to NodeJS, features that will be explored include an IDE (studio app for developing TagUI flows / scripts), orchestrator app (for scheduling automations through time-based or event-based etc), potentially reporting app (for collecting reports of automations done). That release probably would be TagUI v7 or v8.

Prior to that release, there are some changes to be made that are backward in-compatible, to refine and improve user experience. An example would be making Chrome visible mode as the default mode, and retiring PhantomJS mode to encourage use of Chrome headless mode, as most websites are designed and tested to work on Chrome not PhantomJS. And perhaps settling on a file extension such as .tag to standardise file naming. These changes would be in v6.

Prior to v6, this v5.11 aims to round up all the changes since v5.0 packaged release.

**Comment by kensoh** [comment]
Checklist for v5.11 packaged release, copying @siowyisheng for info and to add-on -
- [ ] validate current codebase's positive test signature matches
- [ ] draft updated readme and rpa workshop of new commits
- [ ] final check on readme, any corrections or improvements
- [ ] unzip for windows on windows, put cutting edge version, zip
- [ ] unzip for macos on macos, put cutting edge version, zip
- [ ] unzip for linux on linux, put cutting edge version, zip
- [ ] be aware of unneeded hidden files while zipping (eg .git)
- [ ] consider changing host to TagUI repo's new release
- [ ] and using the new URLs for packaged installations
- [ ] check architecture diagram if any update is needed
- [ ] commit changes and publish new release with summary
- [ ] check through links in readme for incorrect mapping
- [ ] test windows zip on positive test and general tests
- [ ] test macos zip on positive test and general tests
- [ ] test linux zip on positive test and general tests

**Comment by kensoh** [comment]
Created PR above to make general readme improvements before v5.11 release.

After looking through commits, many changes are updated already in readme and are either new readme notes, bug-fixes or minor improvements. Below are the 3 new features that are needed to be added for v5.11 readme. Have made a local edit of readme for these features.

#466 - end_processes script to kill TagUI processes
#461 - support defining regions for OCR and snapshot
#559 - clipboard() helper function to get or put text

**Comment by kensoh** [comment]
I don't have a name for this release yet, for now tentatively Pre-v6 Release because it's meant as a 'snapshot' of the version before the breaking changes are introduced from v6 onwards.

I expect in v7 and v8 there might be backward compatibility breaking changes as new technical roadblocks are discovered. And we should not be held back from doing so, to move towards the future stable state. This prev-v6 and v6 release will let users continue using their existing scripts until they are comfortable to move to v7 and v8.

**Comment by kensoh** [comment]
All done, I'll do a summary of the changes in release notes over the weekend. I'll remove that new release and publish again with the files, otherwise the 1 commit after the release was done shows the commit done for the release happening after the release, which is misleading. First time trying to host the zips here, catch-22, whichever done first will have a momentary gap.

https://github.com/kelaberetiv/TagUI/releases/tag/v5.11.0

**Comment by kensoh** [comment]
(no need re-attach the zips.

I publish with new tag v5.11.1, removed old tag v5.11.0, then re-publish as v5.11.0)

**Comment by kensoh** [comment]
Ok done! - https://github.com/kelaberetiv/TagUI/releases/tag/v5.11.0

I put together the list of changes, write a short 1-liner for them, and add some general notes.

**Comment by kensoh** [comment]
Copying @siowyisheng -

**Comment by kensoh** [comment]
Made some updates the [v5.11 release notes](https://github.com/kelaberetiv/TagUI/releases/tag/v5.11.0) with some forward looking statements - 

---

TagUI is a command-line tool for digital process automation (RPA)

**New Features**
- #559 - clipboard() helper function to read & write
- #466 / #417 - shell script to kill TagUI processes
- #465 - support escape chars in live mode, eg '
- #462 - improve snap step Chrome snapshots
- #461 - support regions for OCR and snapshot
- #442 - support non-terminal usage of TagUI

**Bug Fixes**
- #648 - fix Chrome not closing for macOS & Linux
- #597 - fix PHP warning for newer PHP versions
- #592 - fix select step, change to match exactly
- #553 - fix frame not working issue with Chrome
- #549 - fix using variables dynamically in live mode
- #497 - fix timeout hanging if no visual automation

**General**
- #606 - graceful handling of invalid Python code
- #589 - update readme to use Corretto OpenJDK
- #490 - provide prettified codebase for readability
- #459 - readme add section on TagUI for Python
- #443 - timeout step to update SikuliX timeout
- #423 - enable check step to work in for loop

This release rounds up all enhancements and bug fixes since the last packaged release 8 months ago.

New features worth noting would be the clipboard() helper function to read and write to the clipboard, the end_processes and end_processes.cmd scripts to let users kill all TagUI and integrations processes, and supporting (x1,y1)-(x2,y2) regions as identifiers for read and snap steps.

[Siow Yi Sheng](https://github.com/siowyisheng) has joined AI Singapore and will be taking over future development of TagUI. Coming from a deep business background, he pivoted and made great leaps in tech, both in frontend and backend. The knowledge transfer and handover has begun, and this release is the last release which I'll be driving.

There are going to be very exciting developments next year. Including a TagUI IDE to make developing RPA workflows accessible to everyone, an Orchestrator for scheduling and managing workflows, and a Reporting Dashboard for a one-stop view of the executed workflows.

---

In the interim, v6 is being worked on, which will introduce changes that improve TagUI user experience. For example, using Chrome visible browser by default instead of PhantomJS invisible browser. The .raw .js .log files will not be generated by default as they are irrelevant to most users most of the time. Also, .tag will become the standard file extension for TagUI flow files. Because these improvements may require changes to how users currently use and setup TagUI, this next release will be bumped up to v6.

Other interesting features that Yi Sheng is working on include having the option to generate a Windows batch file or macOS script automatically so that users can double-click on a desktop icon to run the automation, having an option to launch TagUI in live mode directly, adding SHA hash to report option to prevent malicious tampering of auditing results, and visually looking for specified text on the screen. A POC on migrating TagUI from using PhantomJS to Node.js as the execution engine is also underway.
